#!/bin/bash

# Array of filenames
files=(
  "06_Main.go"
  "07_User_Input.go"
  "08_Error_Handling.go"
  "09_Blank_Identifier.go"
  "10_Variables.go"
  "11_Data_Types.go"
  "12_Casting.go"
  "13_Casting_Strings.go"
  "14_If_Conditional.go"
  "15_Strings.go"
  "16_Runes.go"
  "17_Printf.go"
  "18_Time.go"
  "19_Math.go"
  "20_For_Loop.go"
  "21_While_Loop.go"
  "22_Range.go"
  "23_Arrays.go"
  "24_Slices.go"
  "25_Functions.go"
  "26_Return_Multiple.go"
  "27_Function_Errors.go"
  "28_Varadic_Functions.go"
  "29_Passing_Arrays.go"
  "30_Pointers.go"
  "31_Pass_Array_Pointers.go"
  "32_File_IO.go"
  "33_Command_Line.go"
  "34_Packages_Modules.go"
  "35_Maps.go"
  "36_Generics.go"
  "37_Constraints.go"
  "38_Structs.go"
  "39_Composition.go"
  "40_Defined_types.go"
  "41_Associate_Methods.go"
  "42_Protecting_Data.go"
  "43_Getter_Setter.go"
  "44_Encapsulation.go"
  "45_Interfaces.go"
  "46_Concurrency_GoRoutines.go"
  "47_Sleep.go"
  "48_Channels.go"
  "49_Mutex_Lock.go"
  "50_Closures.go"
  "51_Passing_Functions.go"
  "52_Recursion.go"
  "53_Regular_Expressions.go"
  "54_Automated_Testing.go"
  "55_Web_app.go"
  "56_Templates_HTML.go"
  "57_Installation.go"
)

# Loop through the array and create files
for file in "${files[@]}"; do
  touch "$file"
  echo 'package main' > "$file"
done

echo "Files generated successfully."
